/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranscriptsIdRouteImport } from './routes/transcripts.$id'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsIdRoute = TranscriptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TranscriptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/program'
    | '/settings'
    | '/transcripts'
    | '/updates'
    | '/transcripts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/program'
    | '/settings'
    | '/transcripts'
    | '/updates'
    | '/transcripts/$id'
  id:
    | '__root__'
    | '/'
    | '/program'
    | '/settings'
    | '/transcripts'
    | '/updates'
    | '/transcripts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramRoute: typeof ProgramRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptsRoute: typeof TranscriptsRouteWithChildren
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/$id': {
      id: '/transcripts/$id'
      path: '/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof TranscriptsIdRouteImport
      parentRoute: typeof TranscriptsRoute
    }
  }
}

interface TranscriptsRouteChildren {
  TranscriptsIdRoute: typeof TranscriptsIdRoute
}

const TranscriptsRouteChildren: TranscriptsRouteChildren = {
  TranscriptsIdRoute: TranscriptsIdRoute,
}

const TranscriptsRouteWithChildren = TranscriptsRoute._addFileChildren(
  TranscriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramRoute: ProgramRoute,
  SettingsRoute: SettingsRoute,
  TranscriptsRoute: TranscriptsRouteWithChildren,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
