/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUpdatesRouteImport } from './routes/_authenticated/updates'
import { Route as AuthenticatedTranscriptsRouteImport } from './routes/_authenticated/transcripts'
import { Route as AuthenticatedTranscribeTestRouteImport } from './routes/_authenticated/transcribe-test'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProgramRouteImport } from './routes/_authenticated/program'
import { Route as AuthenticatedGeneralRouteImport } from './routes/_authenticated/general'
import { Route as AuthenticatedTranscriptsIdRouteImport } from './routes/_authenticated/transcripts_.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesRoute = AuthenticatedUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranscriptsRoute =
  AuthenticatedTranscriptsRouteImport.update({
    id: '/transcripts',
    path: '/transcripts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTranscribeTestRoute =
  AuthenticatedTranscribeTestRouteImport.update({
    id: '/transcribe-test',
    path: '/transcribe-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramRoute = AuthenticatedProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeneralRoute = AuthenticatedGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranscriptsIdRoute =
  AuthenticatedTranscriptsIdRouteImport.update({
    id: '/transcripts_/$id',
    path: '/transcripts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/general': typeof AuthenticatedGeneralRoute
  '/program': typeof AuthenticatedProgramRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transcribe-test': typeof AuthenticatedTranscribeTestRoute
  '/transcripts': typeof AuthenticatedTranscriptsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/transcripts/$id': typeof AuthenticatedTranscriptsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/general': typeof AuthenticatedGeneralRoute
  '/program': typeof AuthenticatedProgramRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transcribe-test': typeof AuthenticatedTranscribeTestRoute
  '/transcripts': typeof AuthenticatedTranscriptsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/': typeof AuthenticatedIndexRoute
  '/transcripts/$id': typeof AuthenticatedTranscriptsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/general': typeof AuthenticatedGeneralRoute
  '/_authenticated/program': typeof AuthenticatedProgramRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transcribe-test': typeof AuthenticatedTranscribeTestRoute
  '/_authenticated/transcripts': typeof AuthenticatedTranscriptsRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/transcripts_/$id': typeof AuthenticatedTranscriptsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/general'
    | '/program'
    | '/settings'
    | '/transcribe-test'
    | '/transcripts'
    | '/updates'
    | '/transcripts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/general'
    | '/program'
    | '/settings'
    | '/transcribe-test'
    | '/transcripts'
    | '/updates'
    | '/'
    | '/transcripts/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/general'
    | '/_authenticated/program'
    | '/_authenticated/settings'
    | '/_authenticated/transcribe-test'
    | '/_authenticated/transcripts'
    | '/_authenticated/updates'
    | '/_authenticated/'
    | '/_authenticated/transcripts_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transcripts': {
      id: '/_authenticated/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof AuthenticatedTranscriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transcribe-test': {
      id: '/_authenticated/transcribe-test'
      path: '/transcribe-test'
      fullPath: '/transcribe-test'
      preLoaderRoute: typeof AuthenticatedTranscribeTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/program': {
      id: '/_authenticated/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof AuthenticatedProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/general': {
      id: '/_authenticated/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof AuthenticatedGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transcripts_/$id': {
      id: '/_authenticated/transcripts_/$id'
      path: '/transcripts/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof AuthenticatedTranscriptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGeneralRoute: typeof AuthenticatedGeneralRoute
  AuthenticatedProgramRoute: typeof AuthenticatedProgramRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTranscribeTestRoute: typeof AuthenticatedTranscribeTestRoute
  AuthenticatedTranscriptsRoute: typeof AuthenticatedTranscriptsRoute
  AuthenticatedUpdatesRoute: typeof AuthenticatedUpdatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTranscriptsIdRoute: typeof AuthenticatedTranscriptsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGeneralRoute: AuthenticatedGeneralRoute,
  AuthenticatedProgramRoute: AuthenticatedProgramRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTranscribeTestRoute: AuthenticatedTranscribeTestRoute,
  AuthenticatedTranscriptsRoute: AuthenticatedTranscriptsRoute,
  AuthenticatedUpdatesRoute: AuthenticatedUpdatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTranscriptsIdRoute: AuthenticatedTranscriptsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
